




CREATE TABLE `client` (
    `c_client_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `c_client_name` VARCHAR(50) COLLATE UTF8MB4_BIN NOT NULL,
    `c_client_desc` VARCHAR(50) COLLATE UTF8MB4_BIN NOT NULL,
    `c_client_remark` VARCHAR(500) COLLATE UTF8MB4_BIN NOT NULL,
    `c_client_status` VARCHAR(10) COLLATE UTF8MB4_BIN NOT NULL,
    `c_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `c_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `c_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `c_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `c_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`c_client_id`),
    UNIQUE `client_udx01` (`c_client_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;

 
  