




CREATE TABLE `school` (
    `s_school_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `s_client_id` INT(10) UNSIGNED NOT NULL,
    `s_school_name` VARCHAR(50) COLLATE UTF8MB4_BIN NOT NULL,
    `s_school_desc` VARCHAR(50) COLLATE UTF8MB4_BIN NOT NULL,
    `s_school_remark` VARCHAR(500) COLLATE UTF8MB4_BIN NOT NULL,
    `s_school_status` VARCHAR(10) COLLATE UTF8MB4_BIN NOT NULL,
    `s_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `s_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `s_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `s_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `s_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`s_school_id`),
    UNIQUE `school_udx01` (`s_school_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;
 