


CREATE TABLE `login` (
    `a_login_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `a_login_phone` VARCHAR(20) NOT NULL,
    `a_password` VARCHAR(50) COLLATE UTF8MB4_BIN NOT NULL,
    `a_remark` VARCHAR(500) COLLATE UTF8MB4_BIN NOT NULL,
    `a_prefer_language` VARCHAR(5) COLLATE UTF8MB4_BIN NOT NULL,
    `a_status` VARCHAR(10) COLLATE UTF8MB4_BIN NOT NULL,
    `a_locked` TINYINT(1) COLLATE UTF8MB4_BIN NOT NULL,
    `a_fail_count` INT(10) UNSIGNED NOT NULL,
    `a_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `a_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `a_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `a_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `a_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`a_login_id`),
    UNIQUE `login_udx01` (`a_login_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;



