




CREATE TABLE `login_token` (
    `lt_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `lt_login_id` VARCHAR(20) COLLATE UTF8MB4_BIN NOT NULL,
    `lt_device_type` VARCHAR(10) COLLATE UTF8MB4_BIN NOT NULL,
    `lt_push_id` VARCHAR(255) COLLATE UTF8MB4_BIN NOT NULL,
    `lt_login_token` VARCHAR(255) COLLATE UTF8MB4_BIN NOT NULL,
    `lt_token_expiry` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `lt_media_token` INT(10) UNSIGNED NOT NULL,
    `lt_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `lt_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `lt_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `lt_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `lt_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`lt_id`),
    UNIQUE `login_token_udx01` (`lt_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;

