



CREATE TABLE `student_detail` (
    `sd_studend_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `sd_name` VARCHAR(50) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_gender` CHAR(1) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_dob` DATE NOT NULL,
    `sd_email` VARCHAR(300) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_phone` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_address_1` VARCHAR(100) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_address_2` VARCHAR(100) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_address_3` VARCHAR(100) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_remark` VARCHAR(500) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_status` VARCHAR(10) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `sd_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `sd_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sd_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`sd_studend_id`),
    UNIQUE `student_detail_udx01` (`sd_studend_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;