



CREATE TABLE `device_static_key` (
    `dk_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `dk_key` VARCHAR(32) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_device_type` VARCHAR(3) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_encrypt_type` VARCHAR(2) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_version` VARCHAR(5) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `dk_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dk_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dk_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`dk_id`),
    UNIQUE `device_static_key_udx01` (`dk_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;



