



CREATE TABLE `system_parameter` (
    `sp_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `sp_code` VARCHAR(10) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sp_desc` VARCHAR(50) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sp_val` VARCHAR(1024) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sp_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `sp_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sp_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `sp_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `sp_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`sp_id`),
    UNIQUE `system_parameter_udx01` (`sp_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;
	
 