



CREATE TABLE `def_channel` (
    `dc_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `dc_code` VARCHAR(10) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dc_desc` VARCHAR(50) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dc_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `dc_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dc_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dc_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dc_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`dc_id`),
    UNIQUE `def_channel_udx01` (`dc_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;
 
 
  