



CREATE TABLE `def_err_code` (
    `dec_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `dec_code` VARCHAR(10) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dec_desc` VARCHAR(50) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dc_init_code` VARCHAR(50) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dec_disabled` TINYINT(1) NOT NULL DEFAULT '0',
    `dec_create_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dec_create_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dec_update_user` VARCHAR(20) COLLATE UTF8MB4_BIN DEFAULT NULL,
    `dec_update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`dec_id`),
    UNIQUE `def_err_code_udx01` (`dec_id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_BIN;
  